
services:

  # Streamlit App
  streamlit:
    image: streamlit-app:latest
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - mlflow
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1

  # MLflow server
  mlflow:
    image: mlflow/mlflow:2.6.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_ARTIFACT_URI=s3://mlflow-artifacts
    depends_on:
      - minio
      - postgres

  # Postgres for MLflow backend
  postgres:
    image: postgres:15
    container_name: mlflow_postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # MinIO for MLflow artifact storage
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    volumes:
      - minio_data:/data

  # Airflow
  airflow:
    image: apache/airflow:2.9.4-python3.12
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: bUXp6GWgSb2T6Cq2HWY4CmHC3eWqdakg5GMdTWU1GOw= # replace with a generated key
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlflow:mlflow@postgres/mlflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --role Admin --email admin@example.com --firstname Admin --lastname Admin ||
               airflow webserver & airflow scheduler"

volumes:
  pgdata:
  minio_data: